name: Deploy
on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: [self-hosted, florabot]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Florabot
        run: |
          cd ${{ secrets.APP_PATH }}
          git fetch origin main
          git reset --hard origin/main
          docker compose pull
          docker compose --env-file .env up -d --build
          docker image prune -f

          # Wait a few seconds for container startup
          sleep 5

          # Verify container is running
          if docker compose ps | grep -q "discord-florabot"; then
            echo "✅ Florabot container is running"
          else
            echo "❌ Florabot container failed to start"
            exit 1
          fi
